-- MySQL Script generated by MySQL Workbench
-- Wed Nov 10 18:37:14 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `iduser` INT NOT NULL,
  `first_name_user` VARCHAR(30) NULL,
  `email_user` VARCHAR(50) NULL,
  `password_user` VARCHAR(30) NULL,
  `phone` VARCHAR(20) NULL,
  `cpf` CHAR(11) NULL,
  `is_seller` CHAR(1) NULL,
  `sur_name_user` VARCHAR(30) NULL,
  `numero_residencia_idnumero_residencia` INT NOT NULL,
  PRIMARY KEY (`iduser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`seller`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`seller` (
  `idseller` INT NOT NULL,
  `fkuser` INT NOT NULL,
  `commercial_name` VARCHAR(50) NULL,
  `cnpj` CHAR(14) NULL,
  `commercial_email` VARCHAR(50) NULL,
  `whatsapp_number` VARCHAR(20) NULL,
  `instagram_account` VARCHAR(30) NULL,
  `facebook_account` VARCHAR(30) NULL,
  `autentication` CHAR(1) NULL,
  PRIMARY KEY (`idseller`),
  INDEX `fk_seller_user_idx` (`fkuser` ASC) VISIBLE,
  CONSTRAINT `fk_seller_user`
    FOREIGN KEY (`fkuser`)
    REFERENCES `mydb`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`category` (
  `idcategory` INT NOT NULL,
  `name_category` VARCHAR(25) NULL,
  PRIMARY KEY (`idcategory`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`product` (
  `idproduct` INT NOT NULL,
  `name_product` VARCHAR(50) NULL,
  `price_product` DOUBLE NULL,
  `description` VARCHAR(250) NULL,
  `fkcategory` INT NOT NULL,
  `fkseller` INT NOT NULL,
  PRIMARY KEY (`idproduct`, `fkseller`),
  INDEX `fk_product_category1_idx` (`fkcategory` ASC) VISIBLE,
  INDEX `fk_product_seller1_idx` (`fkseller` ASC) VISIBLE,
  CONSTRAINT `fk_product_category1`
    FOREIGN KEY (`fkcategory`)
    REFERENCES `mydb`.`category` (`idcategory`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_seller1`
    FOREIGN KEY (`fkseller`)
    REFERENCES `mydb`.`seller` (`idseller`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`evaluation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`evaluation` (
  `idevaluation` INT NOT NULL,
  `fkuser` INT NOT NULL,
  `note` INT NULL,
  `fkproduct` INT NOT NULL,
  PRIMARY KEY (`idevaluation`),
  INDEX `fk_evaluation_user1_idx` (`fkuser` ASC) VISIBLE,
  INDEX `fk_evaluation_product1_idx` (`fkproduct` ASC) VISIBLE,
  CONSTRAINT `fk_evaluation_user1`
    FOREIGN KEY (`fkuser`)
    REFERENCES `mydb`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_evaluation_product1`
    FOREIGN KEY (`fkproduct`)
    REFERENCES `mydb`.`product` (`idproduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`sub_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`sub_category` (
  `idsub_category` INT NOT NULL,
  `name_sub_category` VARCHAR(25) NULL,
  `fkcategory` INT NOT NULL,
  PRIMARY KEY (`idsub_category`),
  INDEX `fk_sub_category_category1_idx` (`fkcategory` ASC) VISIBLE,
  CONSTRAINT `fk_sub_category_category1`
    FOREIGN KEY (`fkcategory`)
    REFERENCES `mydb`.`category` (`idcategory`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`certification`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`certification` (
  `idcertification` INT NOT NULL,
  `name_certification` VARCHAR(50) NULL,
  PRIMARY KEY (`idcertification`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`order` (
  `idorder` INT NOT NULL,
  `amount` DOUBLE NULL,
  `date_order` DATETIME NULL,
  `fkuser` INT NOT NULL,
  PRIMARY KEY (`idorder`),
  INDEX `fk_order_user1_idx` (`fkuser` ASC) VISIBLE,
  CONSTRAINT `fk_order_user1`
    FOREIGN KEY (`fkuser`)
    REFERENCES `mydb`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`basket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`basket` (
  `fkorder` INT NOT NULL,
  `fkproduct` INT NOT NULL,
  `qtd_inventory` INT NULL,
  `unitary_value` DOUBLE NULL,
  PRIMARY KEY (`fkorder`, `fkproduct`),
  INDEX `fk_request_has_product_product1_idx` (`fkproduct` ASC) VISIBLE,
  INDEX `fk_request_has_product_request1_idx` (`fkorder` ASC) VISIBLE,
  CONSTRAINT `fk_request_has_product_request1`
    FOREIGN KEY (`fkorder`)
    REFERENCES `mydb`.`order` (`idorder`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_request_has_product_product1`
    FOREIGN KEY (`fkproduct`)
    REFERENCES `mydb`.`product` (`idproduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`sellers_certified`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`sellers_certified` (
  `fkcertification` INT NOT NULL,
  `fkseller` INT NOT NULL,
  PRIMARY KEY (`fkcertification`, `fkseller`),
  INDEX `fk_seals_has_seller_seller1_idx` (`fkseller` ASC) VISIBLE,
  INDEX `fk_seals_has_seller_seals1_idx` (`fkcertification` ASC) VISIBLE,
  CONSTRAINT `fk_seals_has_seller_seals1`
    FOREIGN KEY (`fkcertification`)
    REFERENCES `mydb`.`certification` (`idcertification`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_seals_has_seller_seller1`
    FOREIGN KEY (`fkseller`)
    REFERENCES `mydb`.`seller` (`idseller`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`adress`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`adress` (
  `idAdress` INT NOT NULL,
  `logradouro` VARCHAR(60) NULL,
  `number` VARCHAR(8) NULL,
  `state` CHAR(2) NULL,
  `city` VARCHAR(30) NULL,
  `complement` VARCHAR(30) NULL,
  `cep` CHAR(8) NULL,
  `district` VARCHAR(30) NULL,
  `fkuser` INT NOT NULL,
  PRIMARY KEY (`idAdress`, `fkuser`),
  INDEX `fk_Adress_user1_idx` (`fkuser` ASC) VISIBLE,
  CONSTRAINT `fk_Adress_user1`
    FOREIGN KEY (`fkuser`)
    REFERENCES `mydb`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`restock_notification`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`restock_notification` (
  `id_restock_notification` INT NOT NULL,
  `fkuser` INT NOT NULL,
  `fkproduct` INT NOT NULL,
  PRIMARY KEY (`id_restock_notification`, `fkuser`, `fkproduct`),
  INDEX `fk_observer_user1_idx` (`fkuser` ASC) VISIBLE,
  INDEX `fk_observer_product1_idx` (`fkproduct` ASC) VISIBLE,
  CONSTRAINT `fk_observer_user1`
    FOREIGN KEY (`fkuser`)
    REFERENCES `mydb`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_observer_product1`
    FOREIGN KEY (`fkproduct`)
    REFERENCES `mydb`.`product` (`idproduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
